on:
  pull_request:
    types: ["opened", "synchronize", "reopened"]

jobs:
  checkerator:
    runs-on: ubuntu-latest
    name: checkerator-test
    steps:
    - uses: docker://gcr.io/kubebuilder/checkerator:test-7
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
