on:
  pull_request:
    types: [opened, closed, reopened, edited, synchronize]

jobs:
    pr_checks:
        runs-on: ubuntu-latest
        name: verify emoji
        steps:
        - uses: actions/checkout@v2
        - name: verify
          uses: ./hack/release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
